advblog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.views import AboutPage

from blog.sitemaps import PostSitemap

sitemaps = {
	'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('about/',AboutPage.as_view(),name='about'),
    path(
    		'sitemaps.xml',
    		sitemap,
    		{'sitemaps':sitemaps},
    		name='django.contrib.sitemaps.views.sitemap'
    	),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed


app_name = 'blog'

urlpatterns = [
	path('',views.post_list,name='post-list'),
	path('tag/<slug:tag_slug>/',views.post_list,name='post-list-tag'),
	path('detail/<slug:slug>/',views.post_detail,name='post-detail'),
	path('share/<slug:slug>/',views.share_post,name='share'),
	path('feed/',LatestPostFeed(),name='post_feed'),
	path('search/',views.post_search,name='search'),
	
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.

class PublishManager(models.Manager):
	def get_queryset(self):
		return super(PublishManager,self).get_queryset().filter(feature=True)


class Post(models.Model):
	title		= models.CharField(max_length=255)
	slug		= models.SlugField(max_length=255,unique_for_date='publish')
	image		= models.ImageField(upload_to='blog_pics/',default='default.jpg')
	author		= models.ForeignKey(User,on_delete=models.CASCADE,related_name='bog_posts')	
	body		= models.TextField()
	publish		= models.DateTimeField(default=timezone.now)	
	created		= models.DateTimeField(auto_now_add=True)
	updated		= models.DateTimeField(auto_now=True)
	feature		= models.BooleanField(default=False)
	tags		= TaggableManager()

	#need to specify both 
	objects		= models.Manager()  #the default manager
	published	= PublishManager() # our manager

	class Meta:
		ordering = ('-publish',)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:post-detail',kwargs={'slug':self.slug})


class Comment(models.Model):
	post 		= models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
	name		= models.CharField(max_length=255)
	email 		= models.EmailField(max_length=255)
	text 		= models.TextField()
	created		= models.DateTimeField(auto_now_add=True)
	updated		= models.DateTimeField(auto_now=True)
	active		= models.BooleanField(default=True)

	class Meta:
		ordering = ('-created',)

	def __str__(self):
		return 'Comment by {} on {}'.format(self.name,self.post)

blog/forms.py
from django import forms
from .models import Comment

class PostEmailForm(forms.Form):
	name	= forms.CharField(max_length=255)
	email 	= forms.EmailField()
	to	 	= forms.EmailField()
	comment	= forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('name','email','text',)

class SearchForm(forms.Form):
	query = forms.CharField(max_length=355)

blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib import messages
from django.views.generic import TemplateView
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.core.mail import send_mail
from django.db.models import Count

from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.postgres.search import SearchVector,SearchQuery,SearchRank
from taggit.models import Tag

from .models import Post
from .forms import PostEmailForm,CommentForm,SearchForm

def post_list(req,tag_slug=None):
	object_list = Post.published.all()
	tag = None

	if tag_slug:
		 tag = get_object_or_404(Tag,slug=tag_slug)
		 object_list = Post.published.filter(tags__in=[tag])

	paginator = Paginator(object_list,4)
	page = req.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)
	context = {
		'posts':posts,
		'page':page,
		'tag':tag
	}
	return render(req,'blog/post_list.html',context)


def post_detail(req,slug):
	post = get_object_or_404(Post,slug=slug)
	comments = post.comments.filter(active=True)
	form = CommentForm(req.POST or None)
	if form.is_valid():
		comment = form.save(commit=False)
		comment.post = post 
		comment.save()
		messages.info(req,"Your Comment has been Added!")
		return redirect("blog:post-detail",slug=post.slug)
	
	tags = post.tags.values_list('id',flat=True)
	similar_posts = Post.published.filter(tags__in=tags).exclude(id=post.id)
	similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]

	context = {
		'post':post,
		'comments':comments,
		'comment_form':form,
		'similar_posts':similar_posts
	}
	return render(req,'blog/post_detail.html',context)

class AboutPage(TemplateView):
	template_name = 'about.html'

def share_post(req,slug):
	post = get_object_or_404(Post,slug=slug)
	form = PostEmailForm(req.POST or None)
	if form.is_valid():
		email = form.cleaned_data.get('email')
		to	  = form.cleaned_data.get('to')
		name  = form.cleaned_data.get('name')
		comment = form.cleaned_data.get('comment')
		post_url = req.build_absolute_uri(post.get_absolute_url())
		subject  = '{} ({}) recommends you reading {}'.format(name,email,post.title)
		body = 'Read "{}" at {} \n\n {}\'s comments: {}'.format(post.title,post_url,name,comment)
		
		send_mail(subject,body,email,[to])
		msg = 'A "{}" share link has been successfully emailed to {}'.format(post.title,to)
		messages.success(req,msg)
		return redirect('blog:share',post.slug)

	context = {
		'form':form,
		'post':post
	}

	return render(req,'blog/share_post.html',context)


def post_search(req):
	form = SearchForm()
	query = None
	res = []
	if 'query' in req.GET:
		form = SearchForm(req.GET)
		if form.is_valid():
			query = form.cleaned_data.get('query')
			search_vector = SearchVector('title',weight='A') + SearchVector('body',weight='B')
			search_query  = SearchQuery(query)
			res += Post.published.annotate(
				rank=SearchRank(search_vector,search_query)).filter(rank__gte=0.3).order_by('-rank','-publish')
			
			res	+= Post.published.annotate(
					similarity=TrigramSimilarity(
						'title',query)).filter(similarity__gt=0.3).order_by('-similarity')
			res = set(res)
	return render(req,'blog/post_search.html',{'form':form,'res':res,'query':query})

blog/templates/blog/latest_posts.html
<ul>
	{% for post in latest_posts %}
		<li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
	{% endfor %}
</ul>

blog/templates/blog/paginator.html
<div class="container">
	<div class="paginator mx-auto">
		<span class="step-links">
			{% if posts.has_previous %}
				<a href="?page={{ posts.previous_page_number }}" class="btn btn-outline-info m-1">Previous</a>
			{% endif %}
			
			{% if posts.number %}
				<a href="?page={{ posts.number }}" class="btn btn-primary">{{ posts.number }}</a>	
			{% endif %}
			
			{% if posts.has_next %}
				<a href="?page={{ posts.next_page_number }}" class="btn btn-outline-info m-1">Next</a>
			{% endif %}
		</span> 
	</div>
</div>

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load blog_tags %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Post - Detail{% endblock title %}
{% block styles %}
	<link rel="stylesheet" type="text/css" href="{% static 'blog/css/post_detail.css' %}">
{% endblock %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col">
				<h2 class="display-4">{{ post.title }}</h2>
				<div class="imgBx mx-auto">
					<img src="{{ post.image.url }}" class="img-fluid">
				</div>
			</div>	
		</div>
		<div class="row">
			<div class="col">
				<div class="content border my-3" style="background-color: #cff;">
					<p>{{ post.body|markdown }}</p>
					<div class="last">
						<p><small class="text-muted">Published: {{ post.publish|date }}</small></p>
						<p><a href="{% url 'blog:share' post.slug %}">share</a></p>
						<p><h3>-{{ post.author }}</h3></p>
					</div>
					<div class="m-2">
						<p class="tags px-1">Tags :
							{% for t in post.tags.all %}
								<a href="{% url 'blog:post-list-tag' t.slug %}">{{ t.name }} </a>
								{% if not forloop.last %}, {% endif %}
							{% endfor %}
						</p>
					</div>
					
				</div>
			</div>
		</div>		

	</div>

	<div style="background-color: #ddd; padding: 20px; margin: 30px auto;">
		<div class="ml-3 border-bottom d-flex align-items-center justify-content-between ">
			<div class="display-4">Comments: {{comments.count}}</div>
			<div>
			<a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">Add Comment</a>
				</div>
		</div>
		<div class="collapse mydiv" id="collapseExample">
 			<form method="post">
 				{% csrf_token %}
 				{{ comment_form|crispy }}
 				<div class="form-group text-center">
 					<input type="submit" class="btn btn-info" value="Comment">	
 				</div>
 				
 			</form>
		</div>
		{% for c in comments %}
			<div class="container">
				<div class="row my-4">
					<div class="col">
						<div class="comTxt d-flex justify-content-between align-items-center">
							<p>{{ c.name }}:{{ c.text|markdown }}</p>
							<a class="btn btn-primary" data-toggle="collapse" href="#more{{ forloop.counter }}" role="button" aria-expanded="false" aria-controls="more">More</a>
						</div>
						<div class="collapse more" id="more{{ forloop.counter }}">
							<div class="d-flex justify-content-between ">
								<p>email : {{ c.email }}</p>
								<p>On : {{ c.created }}</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
{% endblock content %}

{% block side %}
	{% if similar_posts %}
		<div class="container my-3">
			<h3> Similar Posts</h3>
			<ul>
				{% for p in similar_posts  %}
					<li><a href="{{ p.get_absolute_url }}">{{ p.title }}</a></li>
				{% endfor %}				
			</ul>
		</div>
	{% endif %}
{% endblock side %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load blog_tags %}
{% load static %}
{% block title %}Blog - Home{% endblock %}
{% block styles %}
	<link rel="stylesheet" type="text/css" href="{% static 'blog/css/post_list.css' %}">
{% endblock %}
{% block content %}
	{% if tag %}
		<h2 class="m-4">Posts tagged with "{{ tag.name }}" are....</h2>
	{% endif %}
	<div class="container">
		<div class="row">
			{% for p in posts %}
				<div class="col-sm-12 col-md-6">
					<div class="postBx m-2">
						<div class="imgBx"><img src="{{ p.image.url }}" class="img-fluid"></div>
						<div class="title"><h2><a href="{% url 'blog:post-detail' slug=p.slug %}" class="text-light">{{ p.title }}</a></h2></div>
						<div class="content">
							<div class="desc"><p>{{p.body|markdown|truncatewords_html:20}}</p></div>
							<div class="date"><p>{{p.publish|date}}</p></div>
							<div class="read-more d-flex justify-content-between">
								<a href="{% url 'blog:post-detail' slug=p.slug %}" class="btn btnD1">read more</a>
								<a href="{% url 'blog:share' slug=p.slug %}">Share</a>
								<p class="align-self-center"><a href="">{{p.author}}</a></p>
							</div>
							<div class="tags px-2 mt-2">
								<p>
									Tags : 
									{% for t in p.tags.all %}
										<a href="{% url 'blog:post-list-tag' t.slug%}">{{ t.name }} </a>
										{% if not forloop.last %}, {% endif%}
									{% endfor %}
								</p>
							</div>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>

	{% include 'blog/paginator.html' %}

{% endblock %} 

blog/templates/blog/post_search.html
{% extends 'base.html' %}
{% load blog_tags %}
{% load crispy_forms_tags %}
{% block title %}Search{% endblock %}
{% block content %}
	<h1 class="display-4">Search For Posts </h1>
	<div>
		<form>
			{{ form|crispy }}
			<input type="submit" class="btn btn-primary" value="Search">
		</form>
	</div>
	{% if query %}
		<div class="container my-4">
			<h4 class="display-4">Posts containing "{{ query }}" -</h4><hr>
			<h3>Found {{ res.count }} result{{ res.count|pluralize }}</h3>
			<ul>
				{% for r in res %}
					<li><h4><a href="{{ r.get_absolute_url }}">{{ r.title }}</a></h4></li>
					<p class="lead">{{ r.body|markdown|truncatewords_html:30}}</p>
					<br>
				{% empty %}
					<p class="lead">There are no results for your query!!!</p>
				{% endfor %}
			</ul>
		</div>
	{% endif %}
{% endblock %}

blog/templates/blog/share_post.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Share - Post{% endblock %}
{% block styles %}
{% endblock %}
{% block content %}
	
	{% if sent %}
		<h1>E-mail successfully SENT!</h1>
		<p>
			"{{ post.title }} was successfully sent to {{ form.cleaned_data.to }}"
		</p>
	{% else %}
	<div class="container my-3">
		<form method="post">
			{% csrf_token %}
			<fieldset class="mb-2">
				<legend class="m-2">Share Post</legend>
				{{ form|crispy }}
			</fieldset>
			<input type="submit" class="btn btn-outline-primary" value="Send!">
		</form>
	</div>
	{% endif %}
	
{% endblock %}

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Blog - About{% endblock %}
{% block content %}
	<div class="container">
		<h1>About Page</h1>
	</div>
{% endblock %} 

templates/base.html
<!DOCTYPE html>
{% load blog_tags %}
{% load static %}
<html>
<head>
	<title>{% block title %} Blog {% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
	{% include 'head.html' %}
	{% block styles %}
	{% endblock %}
</head>
<body>
	<header>
		{% include 'navbar.html' %}
		{% if messages %}
			<div class="container-fluid">
				{% for msg in messages %}
					<div class="alert alert-{{msg.tags}}" role="alert">
						{{ msg }}
					</div>
				{% endfor %}
			</div>
		{% endif %}
	</header>
	<main>
		<div class="container">
			<div class="row my-3">
				<div class="col-lg-8">
					{% block content %}
					{% endblock %}		
				</div>
				<div class="col-lg-4">
					<div class="jumbotron jumbotron-fluid">
					  <div class="container">
					    <h1 class="display-4">My Blog</h1>
					    
					    <p class="lead">This is my Blog. I've written {% total_posts %} so far.</p>
					    <p><a href="{% url 'blog:post_feed' %}">Subscribe to my RSS feed</a></p>
					    <hr class="mr-4">
					    <h4 class="display-4">Latest Post</h4>
					    {% show_latest_posts 3 %}
					    <h3>Most Popular Posts</h3>
					    {% get_most_commented_posts as posts %}
					    <ul>
					    	{% for p in posts %}
					    		<li><a href="{{ p.get_absolute_url }}">{{ p.title }}</a></li>
					    	{% endfor %}
					    </ul>
					    
					    {% block side %}
					    {% endblock %}

					    <h4 class="display-4 lead"><a href="{% url 'blog:search' %}">Search</a></h4>
					  </div>
					</div>
				</div>				
			</div>

		
		</div>
		
	</main>
<!-- 	<footer>
		{% include 'footer.html' %}
	</footer> -->
</body>
</html>

templates/footer.html
<div class="container-fluid bg-dark">
	<div class="row">
		<div class="col">
			<a href="">I</a>
		</div>
		<div class="col">
			<a href="">I</a>
		</div>
		<div class="col">
			<a href="">I</a>
		</div>
		<div class="col">
			<a href="">I</a>
		</div>
	</div>
</div>

templates/head.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-lg-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">Create New<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Register</a>
      </li>
    </ul>
  </div>
</nav>